### ISSUE TITLE
doesn't work in strict mode

### ISSUE THREAD

**Issue by jywarren** [mattinsler/resig-class#2]
We found an issue (https://github.com/publiclab/PublicLab.Editor/pull/614) with the following line when trying to compile this in Babel:

https://github.com/mattinsler/resig-class/blob/20c7a168d0e700e91bed8329c7ab3b3517b9e9a9/index.js#L25

It yields `>> TypeError: Attempted to assign to readonly property. at` for this line when running in PhantomJS within a Jasmine test. We're looking for a workaround, just filing this here for reference. 

Looks like some refactors/ rewrites available here: 

https://stackoverflow.com/questions/15050816/is-john-resigs-javascript-inheritance-snippet-deprecated

Thanks!

**Comment by mattinsler** [comment]
I just published version 2.0.0. There is an API change in this version where you need to import the library like the following.

```javascript
const { Class } = require('resig-class');
```

I hope this helps!

**Comment by jywarren** [comment]
Oh wow, thank you!!! Amazing, and many thanks for the swift response!
